#!/bin/bash

echo "Running pre-commit checks..."

# Run your checks
./mvnw validate
./mvnw clean test
./mvnw jacoco:report
./mvnw clean verify
# Check if any of the commands failed
if [ $? -ne 0 ]; then
    echo "Pre-commit checks failed. Commit aborted."
    exit 1
fi

echo "Pre-commit checks passed."
