#!/bin/bash

echo "Running pre-commit checks..."

# Run your checks
./mvnw validate || { echo "Validation failed. Commit aborted."; exit 1; }
./mvnw clean test || { echo "Unit tests failed. Commit aborted."; exit 1; }
./mvnw jacoco:report || { echo "Jacoco report generation failed. Commit aborted."; exit 1; }
./mvnw clean verify || { echo "Verification failed. Commit aborted."; exit 1; }


echo "Pre-commit checks passed."

