#!/bin/bash

echo "Running pre-commit checks..."

# Run your checks
./mvnw validate -Dspring.profiles.active=test || { echo "Validation failed. Commit aborted."; exit 1; }
./mvnw clean test -Dspring.profiles.active=test|| { echo "Unit tests failed. Commit aborted."; exit 1; }
./mvnw jacoco:report -Dspring.profiles.active=test|| { echo "Jacoco report generation failed. Commit aborted."; exit 1; }
./mvnw clean verify -Dspring.profiles.active=test || { echo "Verification failed. Commit aborted."; exit 1; }


echo "Pre-commit checks passed."

